---
- name: Install requirements
  ansible.builtin.package:
    name: "unzip"
    state: present

- name: Check if GRR directories already exists
  ansible.builtin.stat:
    path: "{{ grr_content_dest }}"
  register: grr_installed

- name: Backup Local Config
  when: grr_force_update and grr_installed.stat.exists
  block:
    - name: Check if GRR Backup already exists
      ansible.builtin.stat:
        path: "{{ grr_backup_directory }}"
      register: grr_backup

    - name: Remove Old GRR Backup before update
      ansible.builtin.file:
        path: "{{ grr_backup_directory }}"
        state: absent
      when: grr_backup.stat.exists

    - name: BackUp GRR before update
      ansible.builtin.copy:
        remote_src: true
        src: "{{ grr_content_dest }}/"
        dest: "{{ grr_backup_directory }}"
        owner: "root"
        group: "root"
        mode: "750"

    - name: Remove GRR Folder before update
      ansible.builtin.file:
        path: "{{ grr_content_dest }}"
        state: absent

- name: Download and extract GRR
  ansible.builtin.unarchive:
    src: "{{ grr_download_url }}"
    remote_src: true
    dest: "{{ grr_unarchive_dir }}"
    owner: "{{ grr_web_owner }}"
    group: "{{ grr_web_group }}"
    validate_certs: false
  when: not grr_installed.stat.exists or grr_force_update

- name: Check GRR extracted directory
  ansible.builtin.stat:
    path: "{{ grr_unarchive_dir }}/GRR-{{ grr_version }}"
  register: grr_extracted_directory

- name: Rename GRR extracted directory
  ansible.builtin.command:
    mv {{ grr_unarchive_dir }}/GRR-{{ grr_version }} {{ grr_content_dest }}
  args:
    creates: "{{ grr_content_dest }}"
    removes: "{{ grr_unarchive_dir }}/GRR-{{ grr_version }}"
  when: grr_extracted_directory.stat.exists

- name: Copy Connect File
  ansible.builtin.template:
    src: connect.inc.php.j2
    dest: "{{ grr_content_dest }}/personnalisation/connect.inc.php"
    owner: www-data
    group: www-data
    mode: "0640"
    force: true
  when: grr_force_update and grr_installed.stat.exists

- name: Copy Configuration File
  ansible.builtin.template:
    src: configperso.inc.php.j2
    dest: "{{ grr_content_dest }}/personnalisation/configperso.inc.php"
    owner: www-data
    group: www-data
    mode: "0640"
    force: true

- name: Deploy LDAP configuration
  ansible.builtin.template:
    src: config_ldap.inc.php.j2
    dest: "{{ grr_content_dest }}/personnalisation/config_ldap.inc.php"
    owner: www-data
    group: www-data
    mode: "0640"
    force: true
  when: grr_use_ldap

- name: Change GRR directory owner
  ansible.builtin.file:
    path: "{{ grr_content_dest }}"
    owner: "{{ grr_web_owner }}"
    group: "{{ grr_web_group }}"
    recurse: true
